### ISSUE TITLE
ply importer dosen't for with Double float position 

### ISSUE THREAD

**Issue by tarrabass** [keijiro/PcxEffects2#1]
Hello 
this is the header of my ply files 
Ply importer make a trange texture with that files 

format binary_little_endian 1.0
comment Created by CloudCompare v2.11 alpha (Anoia)
comment Created 12/02/2020 15:00
obj_info Generated by CloudCompare!
element vertex 2606740
property double x
property double y
property double z
end_header

the texture generate doesn't work 
thanks for all your stuff

**Comment by keijiro** [comment]
It's fixed in the main repository.

https://github.com/keijiro/Pcx

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
