### ISSUE TITLE
Using ply Point Clouds with VFX graph

### ISSUE THREAD

**Issue by ibilab** [keijiro/PcxEffects2#2]
Hi, I used Pcx before and I'm trying to catch up with the VFX graph integration and I have a hard time figuring out how to use my .ply clouds with ,it to apply noise based deformations. Do I need to use the point cache baking tool to then transform them into a texture in the VFX graph? I'm missing the connecting piece since I'm just learning the graph's logic.
Thanks

**Comment by keijiro** [comment]
First of all, please check the Pcx repository and its README file.

https://github.com/keijiro/Pcx

Then, check its vfxgraph-example branch.

https://github.com/keijiro/Pcx/tree/vfxgraph-example

If you still have a problem with it, please use the issue tracker of the Pcx repository.
